server:
  port: 9991
vicinity:
  bulletin-board:
    items:
      default-expiration-seconds: 3600 #1 hour,172800 # 2 days
  url: ${VICINITY_URL}
  processType: server
  name: local-vicinity
  env:
    to-do: disable
    acknowledgement: disable
    actor-entered-event: disable
