apiVersion: apps/v1
kind: Deployment  # note: for showcase: this should be a stateful set in a production application
metadata:
  name: boa-retail-db-service
  labels:
    platform: boa
    app: retail
    service: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      platform: boa
      app: retail
      service: db-service
  template:
    metadata:
      labels:
        platform: boa
        app: retail
        service: db-service
    spec:
      containers:
        - name: db-service
          image: mongo:5.0
          imagePullPolicy: Never
          ports:
            - name: db-port
              containerPort: 27017
          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: db-secret
#                  key: MONGO_INITDB_ROOT_USERNAME
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: db-secret
#                  key: MONGO_INITDB_ROOT_PASSWORD
#            - name: MONGO_INITDB_DATABASE
#              valueFrom:
#                secretKeyRef:
#                  name: db-secret
#                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - name: db-config
              mountPath: /etc/mongod.conf
              readOnly: true
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: db-data
              mountPath: /data/db
      serviceAccountName: boa-service-account
      hostname: db
      volumes:
        - name: db-config
          configMap:
            name: db-config
            items:
              - key: mongodb.conf
                path: mongodb.conf
        - name: db-init
          configMap:
            name: db-config
            items:
              - key: mongo-init.js
                path: mongo-init.js
        - name: db-data
          emptyDir: { }    #note: this should be a persistent volume in production
