apiVersion: apps/v1
kind: Deployment
metadata:
  name: boa-retail-advertiser
spec:
  template:
    spec:
      containers:
        - name: advertiser
          image: localhost:5000/boaretail_advertiser
          imagePullPolicy: Always
        - name: advertiser-service
          image: localhost:5000/boaretail_advertiser-service
          imagePullPolicy: Always
