apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/services
namespace: boa

patchesStrategicMerge:
  - redis-service.yaml
  - db-service.yaml
  - hub-service.yaml
  - identity-provider-service.yaml
  - customer-service.yaml