apiVersion: v1
kind: Service
metadata:
  name: boa-retail-redis-service
spec:
  type: NodePort
  clusterIP: 10.111.222.121
  ports:
    - port: 6389
      name: redis-svc-port
      targetPort: redis-port
      nodePort: 30389