version: "3"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    hostname: redis
  database:
    image: mongo
    restart: always
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Architecture
      - MONGO_INITDB_ROOT_PASSWORD=f1rst
      - MONGO_INITDB_DATABASE=architecture_first_001
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    hostname: db
  advertiser-service:
    restart: always
    ports:
      - 10001:3001
    build:
      context: ./external/advertiser-service
  hub-service:
    restart: always
    depends_on:
      - redis
    ports:
      - 10010:3010
    build:
      context: ./external/hub-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROXY_URL=customer:8084
      - ROOT_PATH=/usr/src/app/ui-customer
      - DEBUG=http,router,express:*
  identity-provider:
    restart: always
    depends_on:
      - redis
      - database
    build:
      context: ./identity-provider
    env_file:
      - .env
    environment:
      - TASKLIST_ROOT_PATH=none
    hostname: identity-provider
  merchant:
    restart: always
    depends_on:
      - redis
      - database
      - identity-provider
    ports:
      - 10082:8082
    build:
      context: ./merchant
    env_file:
      - .env
    hostname: merchant
  customer:
    restart: always
    depends_on:
      - redis
      - database
      - identity-provider
      - hub-service
    ports:
      - 5006:5006
      - 10084:8084
    build:
      context: ./customer
    env_file:
      - .env
    environment:
      - HUB_URL=ws://hub-service:10010
    hostname: customer
  cashier:
    restart: always
    depends_on:
      - redis
      - database
      - identity-provider
    ports:
      - 10083:8083
    build:
      context: ./cashier
    env_file:
      - .env
    hostname: cashier
  advertiser:
    restart: always
    depends_on:
      - redis
      - database
      - identity-provider
    ports:
      - 10085:8085
    build:
      context: ./advertiser
    env_file:
      - .env
    environment:
      - DYNAMIC_ACTOR_GROUP=Advertiser
    hostname: advertiser
  vendor:
    restart: always
    depends_on:
      - redis
      - database
      - identity-provider
    ports:
      - 10086:8086
    build:
      context: ./vendor
    env_file:
      - .env
    hostname: vendor