apiVersion: v1
kind: Service
metadata:
  name: boa-retail-db-service
spec:
  type: ClusterIP
  selector:
    platform: boa
    app: retail
    service: db-service
  ports:
    - port: 27027
      name: db-svc-port
      targetPort: db-port
