apiVersion: v1
kind: Service
metadata:
  name: boa-retail-identity-provider-service
spec:
  type: ClusterIP
  selector:
    platform: boa
    app: retail
    service: identity-provider
  ports:
    - port: 9091
      targetPort: svc-port
