apiVersion: v1
kind: Service
metadata:
  name: boa-retail-redis-service
spec:
  type: ClusterIP
  selector:
    platform: boa
    app: retail
    service: redis-service
  ports:
    - port: 6389
      name: redis-svc-port
      targetPort: redis-port
