kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boa-cluster-readonly-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boa-cluster-readonly-role
subjects:
  - kind: ServiceAccount
    name: boa-service-account
    namespace: boa