kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boa-cluster-readonly-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods
      - services
      - jobs
      - cronjobs
      - configmaps
      - secrets
    verbs: ["get", "list", "watch"]