server:
  port: 8084
vicinity:
  name: local-vicinity
  host: ${VICINITY_HOST}
  port: ${VICINITY_PORT}
  task-list:
    root-path: ${TASKLIST_ROOT_PATH}
identity-provider:
  private-key: ${PASS_KEY}

data:
  database:
    connectionString: ${DB_CONNECTION_STRING}
    name: ${DB_NAME}
redis:
  host: ${REDIS_HOST}
hub:
  host: ${HUB_URL}



